---
downloads: ~/.ansible-downloads/

general:
    local_home: "{{ lookup('env','HOME') }}"
    user_name: "{{ lookup('env', 'USER') }}"

apt_packages:
    - cowsay
    - vim
    - sudo
    - apt-transport-https
    - ca-certificates
    - software-properties-common
    - curl
    - git
    - git-doc
    - git-email
    - git-gui
    - gitk
    - xclip
    - tmux
    - tree
    - direnv
    - entr
    - snapd
