---
  - name: Update repositories cache
    apt:
      update_cache: yes

  - name: Install basic packages
    apt:
      name: "{{ apt_packages }}"
      state: "latest"
  
  - name: Remove useless packages from the cache
    apt:
      autoclean: yes

  - name: Remove dependencies that are no longer required
    apt:
      autoremove: yes
