---
  - name: Update repositories cache
    apt:
      update_cache: yes

  - name: Install basic packages
    apt:   name={{ item }} state=latest 
    with_items:
      - vim
      - sudo
      - git
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
      - git-doc
      - git-email
      - git-gui
      - gitk
      - xclip
      - tmux
      - tree
  
  - name: Remove useless packages from the cache
    apt:
      autoclean: yes

  - name: Remove dependencies that are no longer required
    apt:
      autoremove: yes
